
apiVersion: v1
kind: Service
metadata:
  namespace: weather
  name: weatherdb-cluster-service
  labels:
    app: weatherdb
spec:
  type: ClusterIP
  clusterIP: 10.43.1.1
  ports:
    - port: 30431
      targetPort: 5432
  selector:
    app: weatherdb
