apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: weather
  name: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
