apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: weather
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
